### ISSUE TITLE
start_sim.launchの起動について

### ISSUE THREAD

**Issue by shunsugar** [KBKN-Autonomous-Robotics-Lab/IGVC2023-src#11]
pull requestの質問が不十分だと思うので、整理して質問します。

start_sim.launchをroslaunchを使って起動しようと思っているのですが、

roslaunch  #####  start_sim.launch

の#####の部分がわからないです。僕の中では、ROSノードのパッケージ名が入ると思っているのですが、それがどこにあるのかよくわからないです。

よろしくお願いいたします。

**Comment by koki0624** [comment]
基本的なパッケージの構成
package_name
|-- CMakeList.txt
|-- package.xml
|-- src (scripts)：ノードのファイルを置く場所
|-- include
|-- launch：複数のノードをまとめて起動できるlaunchファイルを置く場所

catkin build (cmコマンド) により、以上の構成をもつディレクトリをパッケージとして登録することができます。
roslaunchコマンドは、登録されているパッケージの中のlaunchディレクトリを探し、その中にあるlaunchファイルを実行するコマンドです。

今回の場合、"igvc2023" というパッケージのlaunchディレクトリの中にstart_sim.launchがある状態で、catkin build (cm) が成功すれば、
>> roslaunch igvc2023 start_sim.launch
で起動することができます。

**Comment by Alpaca-zip** [comment]
@shunsugar 問題が解決した様なら、issuesをcloseしてもらえると助かります。
closeした場合にも、issues->closedから過去のissueを見ることができます！

**Comment by shunsugar** [comment]
すみません！まだ、解決していないです。

説明はとても分かりやすく、理解しました。しかし、catkin buildが成功していないのか、roslaunchをすると、次のようにエラーが出ます。

#####
ubuntu@2e821fc7c3b3:~/catkin_ws/src$ roslaunch igvc2023 start_sim.launch

RLException: [start_sim.launch] is neither a launch file in package [igvc2023] nor is [igvc2023] a launch file name
The traceback for the exception was written to the log file
#####

catkin buildでは、赤字ではないですが次のようなエラーが出て、権限がないと否定されました。どのように対処したら良いのでしょうか。よろしくお願いいたします。

#####
PermissionError: [Errno 13] Permission denied: '/home/ubuntu/catkin_ws/devel/.catkin'
#####

**Comment by shunsugar** [comment]
closedになったので、reopenします。

**Comment by koki0624** [comment]
ubuntuには"root"ユーザという管理者的なユーザがあって、基本的にはそれとは別のユーザ（今だったら"ubuntu"ユーザ）として動かしています。docker buildをするときは"root"ユーザとしてdockerfile内のコマンドを実行していて、このリポジトリをgit cloneしてcatkin_ws/srcにもってくるのもroot権限のもとで実行されています。なので、"ubuntu"ユーザとしてcatkin buildをしようとすると「権限がありません」ということになります。
つまり、root権限のもとで、"ubuntu"ユーザに権限を与えれば解決できます。
>> sudo chown -R $USER:$USER .
このコマンドはroot権限のもとで(sudo)、今いるディレクトリ( . )以下のすべてのファイル( -R )の所有者を、$USER（ユーザ名を指す環境変数で今だったらubuntu）に変更するコマンドです。これを、catkin_ws 以下に対して実行すれば解決すると思います。
ただ、すべてのファイルの所有者を変更するので、ファイルが多いと膨大な時間がかかります。なので、
>> catkin clean
で srcディレクトリのみ残してから実行することをお勧めします。その後再度catkin buildをすれば解決するはずです。

**Comment by shunsugar** [comment]
catkin clean
sudo chown -R $ubuntu:$ubuntu .
catkin build
roslaunch igvc2023 start_sim.launch

の順で実行したのですが、うまくいきませんでした。

**Comment by koki0624** [comment]
@shunsugar catkin build でpermission erroeは出た？

**Comment by shunsugar** [comment]
PermissionError: [Errno 13] Permission denied: '/home/ubuntu/catkin_ws/devel/.catkin'
と出ました。

**Comment by shunsugar** [comment]
catkin_ws/srcでさっきの手順をやっていたのですが、それが原因ですかね。

**Comment by koki0624** [comment]
もしかして、catkin clean の段階でpermission error出てない？
だとしたら sudo をつけて実行してみて。

**Comment by shunsugar** [comment]
PermissionError: [Errno 13] Permission denied: 'package.cmake'

catkin cleanで上のエラー出てました。

sudo catkin cleanつけたらエラーなくなったんですが、roslaunchがうまくいきませんでした。

**Comment by koki0624** [comment]
catkin clean したらもう一度 catkin build です。

**Comment by shunsugar** [comment]
sudo catkin clean
sudo chown -R $ubuntu:$ubuntu .
catkin build
roslaunch igvc2023 start_sim.launch

でダメでした。

**Comment by koki0624** [comment]
permission errorはもう出てない？roslaunchで出るエラーはどんな？

**Comment by shunsugar** [comment]
roslaunchのエラーはこれです。

ubuntu@2e821fc7c3b3:~/catkin_ws$ roslaunch igvc2023 start_sim.launch
RLException: [start_sim.launch] is neither a launch file in package [igvc2023] nor is [igvc2023] a launch file name
The traceback for the exception was written to the log file

**Comment by koki0624** [comment]
roslaunchで出てるエラーは書いてある通りで、igvc2023っていうパッケージのlaunchディレクトリの中を探してもstart_sim.launchはありません　と言ってます。
あとcatkin build時のwarningは無視でいいです。エラーなく終わればOK。

**Comment by koki0624** [comment]
ごめん、勝手にコンテナにアクセスしてちょっといじったんだけど、おそらくcatkin buildをしたターミナルでそのまま実行しようとしてたことが原因だったと思います。実は、catkin buildをしたあとは以下のコマンドを実行する必要があります。
`source ~/catkin_ws/devel/setup.bash`
これによりパッケージの情報が更新されるのですが、今はターミナルを新しく開いたとき、自動で実行されるように設定してあります。catkin buildを実行しても変化がない場合はこれが原因であることがあるので、上記のコマンドを直接実行するか、新しくターミナルを開いて再度実行すると解決する場合があります。

**Comment by Alpaca-zip** [comment]
`source ~/catkin_ws/devel/setup.bash `が長いと感じるなら`source ~/.bashrc`でも同様の効果得られるのでおすすめです。編集した内容が反映されてないなーってときにもこのコマンド実行すると直ることが多いです。

**Comment by shunsugar** [comment]
どっちの場合でも解決出来ました。何度もありがとうございます。
