### ISSUE TITLE
enブランチの削除について

### ISSUE THREAD

**Issue by takamooori** [KBKN-Autonomous-Robotics-Lab/IGVC2023-src#16]
練習でenブランチを作成しましたがこのブランチの削除方法がわかりません。

よろしくお願い致します。

> @Alpaca-zip @koki0624

**Comment by Alpaca-zip** [comment]
さっきenっていうブランチは削除しちゃいましたが、練習のため再度作りました。
ブランチの削除は以下の手順でできると思います。権限の関係でできない可能性もあるので、その時は教えてほしい！
①
![スクリーンショット (369)](https://user-images.githubusercontent.com/84959376/209800452-1339c4e3-19bd-49cc-a340-6985e01f77c5.jpg)
②
![スクリーンショット (370)](https://user-images.githubusercontent.com/84959376/209800517-cac1f523-9c8d-4c86-b6f3-29f005b93df1.jpg)

**Comment by Alpaca-zip** [comment]
別件で補足ですが、issuesのAssigneesとLabelsは付けてもらえると、誰に対してのどのような内容なのかが一目で分かるのでお勧めです。一先ずは私がつけちゃいます。
![スクリーンショット (371)](https://user-images.githubusercontent.com/84959376/209801034-2ce4bc77-2738-4334-899e-718510e6b195.jpg)

**Comment by takamooori** [comment]
ありがとうございます。
下のように削除マークが出てきません。
権限の関係でしょうか。

![image](https://user-images.githubusercontent.com/120566087/209801755-6f78e945-4fb2-4261-91ce-6e8ad0472ae0.png)

**Comment by takamooori** [comment]
またAssigneesとLabelsについてですが、どこからつけるのでしょうか。
歯車マークが削除マーク同様ありませんでした。

**Comment by Alpaca-zip** [comment]
今確認してみたところ、write権限が付与できていませんでした。すみません。
これでどうでしょうか。

**Comment by takamooori** [comment]
両方ともできました。
ありがとうございます！！
