### ISSUE TITLE
機体SUSの組み立て

### ISSUE THREAD

**Issue by Alpaca-zip** [KBKN-Autonomous-Robotics-Lab/IGVC2023-src#18]
研究室にSUSが届きましたので、暫定的な機体フレームの組み立てを行ってください。
**タスク**
- [x] フレームの組み立て
- [x] タイヤの取り付け機構の考案
- [ ] ハードウェアにおける問題点の洗い出し

**Comment by Yutarop** [comment]
研究室に届いたSUSとOwncluodに乗っている設計図がちがうと思われます！
設計図で測ったところ130,180,450ｍｍが四本ずつ必要なのですが、箱の中には450が3本しかありませんでした。
@kengohozumi

**Comment by Alpaca-zip** [comment]
あらあら。
どこのフレームが足りていないのか画像も貼り付けていただけますか？

**Comment by shunsugar** [comment]
![スクリーンショット (1187)](https://user-images.githubusercontent.com/120554165/212607031-2835a060-54c5-4c05-9fe6-cd97de511e59.png)
owncloud上にあったのは画像の設計図なのですが、画像中の濃い緑のフレームが足りませんでした。

**Comment by Yuta-0711** [comment]
連絡遅くなり申し訳ございません。
発注した機体のデータについて、４年生と先生にはメールで共有をしていたのですが、もしかしたらowncloudの方へのアップロードを行っていなかったかもしれません。
後ほどデータをowncloudへのアップロードおよびLINEグループの方にお送りしますので、そちらの方を確認してみてください。

**Comment by Yutarop** [comment]
承知しました。ありがとうございます。

**Comment by Alpaca-zip** [comment]
一応、ここにもSUSのデータファイル置いときます。なぜかteamsの方には貼れませんでした...。不便。
[chassis.zip](https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/files/10426918/chassis.zip)

![スクリーンショット (430)](https://user-images.githubusercontent.com/84959376/212709236-e745420c-8a33-425a-8c18-abdf81c0101f.png)

**Comment by Yutarop** [comment]
機体の大枠は組み立てることができたのですが、画像の赤い矢印のような場所の長さが正確に分からなかったので、今はとりあえず取り付けただけになっています。SUSのアプリで長さを測ろうとしてみましたが、二枚目の画像のように端がずれてしまっていおり、正確に長さを測る事が出来ませんでした。
![スクリーンショット (116)](https://user-images.githubusercontent.com/120556494/213640439-b7f9a53e-1d95-4cf2-9473-f06234fc9f06.png)
![IMG_3657 (1)](https://user-images.githubusercontent.com/120556494/213640926-1d8abf30-f474-4891-9524-9844dab0bb09.jpeg)
![IMG_3660](https://user-images.githubusercontent.com/120556494/213640952-95f9aba8-2adb-448a-a3ca-baeabdd0dee6.jpg)

**Comment by Yuta-0711** [comment]
お疲れ様です。

赤矢印で示されたところの距離は特に決めていません。
画像の赤矢印で示されたフレームの左側はキャスターの幅に合わせる必要があり、右側のフレームはペイロードを乗せるために取り付けているので、ペイロードを乗せる位置によって変化します。

**Comment by Yutarop** [comment]
承知しました。
ありがとうございます！

**Comment by Alpaca-zip** [comment]
長いことハードウェアの進捗を確認できていませんがどのような状況でしょうか？
タイヤの取り付けは完了しましたか？

**Comment by Yutarop** [comment]
現在、保泉さんにMDFの加工を行っていただいています！
終わり次第、タイヤを取り付けたいと思います 🙇‍♂️

**Comment by kengohozumi** [comment]
もうタイヤの取り付ける設計とバッテリーなどを固定する前方内部の設計は完成したのですが、レーザーカッターがエラーが出て加工ができない状況です、、、

**Comment by Alpaca-zip** [comment]
> もうタイヤの取り付ける設計とバッテリーなどを固定する前方内部の設計は完成したのですが、レーザーカッターがエラーが出て加工ができない状況です、、、

個人で解決できそうならいいですが、出来なさそうなら先生に聞くかこのissueで相談してください。

**Comment by kengohozumi** [comment]
レーザーカッターについて先生に相談したところ
故障しているみたいなので今日レーザーカッターを修理にもっていきました。
