### ISSUE TITLE
モジュール配置およびタイヤ取り付け

### ISSUE THREAD

**Issue by Yuta-0711** [KBKN-Autonomous-Robotics-Lab/IGVC2023-src#20]
機体の組み立て終了もしくは、機体の組み立てと並行して行ってください。
もちろんタイヤの固定方法で、鉄板ではなく新たに別の方法で固定を行いたい場合は、それに合わせた取り組みを行ってください。

**タスク**
- [x] 機体に乗せるモジュールの配置決め
- [x] MDF加工
- [x] タイヤの取り付けに合わせた取り組み(鉄板で取り付ける場合は鉄板の発注)
- [x] LiDAR関連の取り付け(つくチャレおよびIGVCのルールに合わせる)

**Comment by kengohozumi** [comment]
@Yuta-0711 すみません　ペイロードの配置なんですが去年はどのように配置を行ったのですか？何か重心の計算して配置しました、、？

**Comment by Yuta-0711** [comment]
ペイロードの配置について、去年は特に重心の計算はしないで配置を行い、ひもで結んで固定をしていました。
配置していた位置は去年のデザインレポートで確認できます。

配置位置の決定は、機体の構造を話し合っているときに、「ここにペイロードおけばいい」程度でしか考えておらず、デザインレポートを書く過程でメリットを捻りだして付け加えました。
