### ISSUE TITLE
外装作成

### ISSUE THREAD

**Issue by Yuta-0711** [KBKN-Autonomous-Robotics-Lab/IGVC2023-src#21]
機体の組み立て終了しだい取り組んでください。

**タスク**
- [x] 外装に用いる素材の決定
- [x] サイズに合わせた外装作成
- [x] E-STOPやLEDの取り付け(ルール参照)
- [x] ファンなどを取り付け(検討)

**Comment by Yutarop** [comment]
**(進捗)**
昨年度と同じ素材で外装を作っています。機体のサイズに合わせて素材を切る所までは終了しました。次回は、足りなかった白色のガムテープを用意し、素材をつなげる作業に取り掛かります。

![外装](https://user-images.githubusercontent.com/120556494/219608012-2ec361e0-2422-4d6a-a8fe-cf885efdbf7c.jpg)
