### ISSUE TITLE
ロボットモデルの名前変更に関しての質問

### ISSUE THREAD

**Issue by shunsugar** [KBKN-Autonomous-Robotics-Lab/IGVC2023-src#26]
[https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/pull/24](url)

でorange2022からorangeに変更しようと思うのですが、ブランチ名はfix/start_simの方がいいですか？

![スクリーンショット (27)](https://user-images.githubusercontent.com/120554165/213097073-c0253d29-2ef9-48a3-ae5f-17d2bf24f432.png)

**Comment by shunsugar** [comment]
https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/pull/24

**Comment by koki0624** [comment]
fix/start_simブランチでいいと思います。
https://github.com/orgs/KBKN-Autonomous-Robotics-Lab/teams/basic-developers/discussions/2
森が同じブランチで作業を引き継ぐときのやり方を載せてくれてるので参照してください。
もし保泉くんと連携をとっていれば大丈夫だけど、同じ作業をしている可能性があるので直で連絡するかAssignして知らせてあげてください。

**Comment by shunsugar** [comment]
わかりました！
ありがとうございます！！
