### ISSUE TITLE
tty/ACMに追加ついて

### ISSUE THREAD

**Issue by kengohozumi** [KBKN-Autonomous-Robotics-Lab/IGVC2023-src#32]
robot_localizaitionのnavsat_transform_nodeを使う上でGPSのtty/ACMの追加が必要で、
追加の方法がわかりません、、

**Comment by koki0624** [comment]
https://github.com/orgs/KBKN-Autonomous-Robotics-Lab/teams/basic-developers/discussions/6

USBデバイスをDockerコンテナ内で使うための手順をまとめたので、これを見てやってみてください。上手くいかなければこちらにコメントしてください。

**Comment by koki0624** [comment]
https://www.ikko-lab.k.hosei.ac.jp/gitbucket/tsukuba2022/orange2022/blob/master/config/70-sensors.rules

gitbucketの方につくばで使っていたudevルールのファイルがあるので、これも参考にしてみてください。最新版じゃなかったかもしれないので、その点はご了承を。

**Comment by kengohozumi** [comment]
ありがとうございます！
参考に追加してみます
