### ISSUE TITLE
白線認識について

### ISSUE THREAD

**Issue by kengohozumi** [KBKN-Autonomous-Robotics-Lab/IGVC2023-src#33]
白線認識の機能追加を始めようと思います
カメラについて触れてきてなかったので苦戦しそうです、、。

**Comment by kengohozumi** [comment]
@koki0624 去年igvcの白線認識の発表をしていたのを覚えています。改善点や反省点、プログラムを作成する上で参考にしたwebサイトなど教えていただけないでしょうか、、？

**Comment by kengohozumi** [comment]
yoloやopen CVなど様々認識に方法があって悩んでいます、、、

**Comment by koki0624** [comment]
> @koki0624 去年igvcの白線認識の発表をしていたのを覚えています。改善点や反省点、プログラムを作成する上で参考にしたwebサイトなど教えていただけないでしょうか、、？

去年は、白線認識のプログラムは先輩方のものを改良する形で作成しました。白線の追従（ナビゲーション）の部分に関してはほぼオリジナルです。技術的な部分ではあらゆるサイトを参考にしましたが、アルゴリズムの部分で参考にしたものはほぼありません。

改善点やアイデアはありますが、それを伝えるにはアルゴリズムの説明も必要になります。その前に、今回のIGVCに向けてどの程度ソフトに手を加えようと考えているかを聞いておきたいです。
例えば、ほぼ1から作り変えたいのか、改良する形で作りたいのか、あるいはそのままでもいいのか、とか。

**Comment by kengohozumi** [comment]
ありがとうございます。

先輩方のを参考にさせていただいて、それを改良して作成したいです。
アルゴリズムはかなり複雑なものですか？

白線の追従というのは自己位置推定と併用して行っていたということですか？

**Comment by koki0624** [comment]
> 先輩方のを参考にさせていただいて、それを改良して作成したいです。
アルゴリズムはかなり複雑なものですか？

了解です。アルゴリズムをここで1から文字で説明するのは難しいので、とりあえず今伝えられる情報を伝えておきます。
1. ownCloud -> arl -> 2022 / IGVC / デザレポ / 発表用 　の中に、「IGVC2022白線認識アルゴリズム」と、「IGVC経路計画システム」の発表資料があるので、一度見てみてください。

2. [igvc2022/launch - GitBucket](https://www.ikko-lab.k.hosei.ac.jp/gitbucket/igvc2022/src/tree/master/igvc2022/launch)
本番に起動していたのは主に以下の2つのlaunchファイルなので、使っていたプログラムはここから追ってもらえれば分かるかと思います。ちなみに、"line_detection"の文言があるものが白線認識に関わるものになります。
	- start.launch （デバイスの起動など）
	- move_base_test.launch （走行開始）
3. 発表資料でざっくりの理解はしてもらえるかなと思いますが、細かい部分はプログラムを見ないと分からないと思います。ただ、人に読まれることを意識してない箇所もあるので、分からないところは質問してください。必要なら直接教えるので連絡してください。

<br>

> 白線の追従というのは自己位置推定と併用して行っていたということですか？

その通りです。gmappingでSLAMによる自己位置推定をしながら、local_goal_setter というノード（自作）で、逐次的に仮のゴールをmove_baseに設定し続けることで走行しています。

**Comment by kengohozumi** [comment]
ありがとうございます！
発表資料を見ながら作成してみます。
追加が終わったら反省点や改善点をお願いします。

**Comment by kengohozumi** [comment]
すいません　git Bucketのigvc2022の中が見れないのですが、、どうやって見れますか？
![image](https://user-images.githubusercontent.com/83738796/217839095-bcc2b305-2b8b-4cbf-bfeb-3164060cac57.png)

**Comment by koki0624** [comment]
サインインすれば見れると思う。

**Comment by Yutarop** [comment]
歴代の先輩が白線認識について書いた文献がネット上に掲載されていたので一応参考として共由させていただきます 😃 
[白線認識_1.pdf](https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/files/10702777/_1.pdf)
