### ISSUE TITLE
白線認識プログラムの作成

### ISSUE THREAD

**Issue by kengohozumi** [KBKN-Autonomous-Robotics-Lab/IGVC2023-src#35]
- [x] 先輩方が作成したigvc2022のline_detectionの追加
- [ ] 昨年のプログラム解読
- [ ] 機能追加と改善
- [ ] Gazebo上でのシュミレーション実験

3月まで(目安)

- [ ] 中庭での実機実験(パラメータ調整)

**Comment by Yutarop** [comment]
現在先輩方が作成したigvc2022のline_detectionの追加を行っているのですが、rosdepのコマンドを入力した際に、以下の画像のようなエラーが出てしまいました。(画像1)ngeometry_msgsのパッケージについてネットで調べてみましたが、geometry_msgsについての情報が少なく、package.xmlのファイルからngeometry_msgsを消して、roslaunch igvc2023 start_sim.launchのコマンドを実行したところ、おそらくですが正常に動きました。(画像2)　ngeometry_msgsについて教えていただけないでしょうか 😲 



**（画像1)**
![image](https://user-images.githubusercontent.com/120556494/218403408-5d0210d1-13f7-4c51-a394-06d5c516dabc.png)
**（画像2）**
![image](https://user-images.githubusercontent.com/120556494/218405992-9ed0259e-0bb2-415c-b0d7-66084346e040.png)

**Comment by koki0624** [comment]
ごめん、多分普通にタイプミスです・・・
package.xml は正直あんまり丁寧に書いてないので、この際igvc2023のやつを参考に書き直してもいいかもです。とりあえず正常に動いたようで何よりです。

**Comment by Yutarop** [comment]
承知しました！　ありがとうございます💡

**Comment by koki0624** [comment]
白線認識と追従に関して、改善点のアイデアをまとめておきます。文章で表現するのが難しくて、何言ってるかわからないかもです。申し訳ない。

### 白線認識に関して

**1. カメラの歪み補正（undistortion）の処理をルックアップテーブルで行う（シミュレーション画像＋MATLABで可能であることは確認済）**
  - チェスボード使ってカメラパラメータ求めてOpenCVの関数使う方法よりも、視野が広そう、ブラックボックスもない、C++で実装すれば処理が速いかも。
  - 現状、歪み補正画像からr-theta画像への変換はルックアップテーブルでやっているので、組み合わせれば元画像からr-thetaへ直接変換もできるのでは。
  - 何ならr-thetaからLiDAR情報への変換もルックアップテーブル的な処理で省略できるのでは。

**2. 元画像 ⇒ 歪み補正画像 ⇒ 白線認識画像 ⇒ r-theta画像 ⇒ LiDAR情報 ⇒ Costmap　の手順を省略して処理を低減する**
  - 例えば、元画像から直接の白線認識と、1のアイデアでの変換ができれば、
  元画像 ⇒ 白線認識画像 ⇒ LiDAR情報 ⇒ Costmap
  と省略できるはず
  - さらに、Costmapのpluginを自作し、白線認識画像からCostmapを生成することができれば、
  元画像 ⇒ 白線認識画像 ⇒ Costmapと省略できるはず
