### ISSUE TITLE
計画表

### ISSUE THREAD

**Issue by kengohozumi** [KBKN-Autonomous-Robotics-Lab/IGVC2023-src#49]
IGVCの計画表を作りました。
https://onedrive.live.com/edit.aspx?resid=24807E0D79D10ED4!29150&ithint=file%2cxlsx&authkey=!ADw6wiXv9Dp4oGI

**Comment by Alpaca-zip** [comment]
Issueベースでタスク管理をしていくのであればGithubのProjectsで事が足りるように思いますがいかがですか？
https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/discussions/46#discussion-4892932

<img src="https://user-images.githubusercontent.com/84959376/223299608-1072a961-03bd-4e6f-ab89-ca37e38b7a03.png" width="600px">

**Comment by Alpaca-zip** [comment]
優先度については設定するのは難しいかもですが、期限はぱっと見でわかるRoadmapという機能がProjectsにあります。以下の記事を参考にしてみてください。
https://github.blog/changelog/2023-01-31-roadmap-in-projects-public-beta/

どういう風にタスク管理するかはお任せします。
