### ISSUE TITLE
robot_pose_ekfを変更

### ISSUE THREAD

**Issue by Alpaca-zip** [KBKN-Autonomous-Robotics-Lab/IGVC2023-src#5]
githubを使った開発に慣れてもらうために、簡単なタスクを用意しました。
Assigneesに割り当てられた人は以下のタスクを行ってください。
- ローカルリポジトリのブランチを切って`feature/ekf_localization`というブランチ名を付ける
- `tsukuba2022`というROSパッケージの中で使っている`robot_pose_ekf`を`ekf_localization`に変更してください
- 一通りバグが無いことを確認したら、リモートにpushしてプルリクエストを提出

このタスク完了後は、IGVCに向けて各自ブランチを切って適宜プルリクエストを出してもらって構いません。時間が空いてるときにレビューしてマージします。

**タスク**
- [ ] igvc2023-srcへのekf_localizationの実装

**Comment by Alpaca-zip** [comment]
@koki0624 質問に気づけるようにアサインしときます。

**Comment by bvbnatsu** [comment]
`robot_pose_ekf` は`tukuba2022`のファイル内で使われているもの全てを変更すればいいのですか。

**Comment by Alpaca-zip** [comment]
@bvbnatsu 返信遅れてごめん！そういうことです。下のurl参考にしてみるといいかもしれません。

https://qiita.com/srs/items/7e8454d4d616983e5cb8

**Comment by bvbnatsu** [comment]
ありがとうございます！

**Comment by kengohozumi** [comment]
すみません　robot_localizationの変更をしてシュミレーションをしようと思っているのですが、start_simのロボットを動かすにはどうしたいいのでしょうか？　cmd_velはどこから設定しますか？

**Comment by Alpaca-zip** [comment]
@kengohozumi 
キーボードから動かす場合には以下のコマンドを実行してください。
`rosrun teleop_twist_keyboard teleop_twist_keyboard.py`

**Comment by kengohozumi** [comment]
ありがとうございます
キーボードから動かしてrobot_localizationが適用できているか確認ってできますか？

**Comment by Alpaca-zip** [comment]
@kengohozumi 
まずは`rosrun rqt_tf_tree rqt_tf_tree`でrobot_localoizationが適切にTFを発行しているかを確認してみてください。
次に、rvizでrobot_localoizationを適用する前のオドメトリと後のオドメトリを比較してみると良いと思います。
あとでコードレビューもするので再度プルリクエストを出してください。

**Comment by kengohozumi** [comment]
適用する前のオドメトリと後のオドメトリを比較するというのはrobot_pose_ekfとrobot_localizationを比較するという意味でしょうか？

**Comment by kengohozumi** [comment]
RROR: cannot launch node of type [robot_localization/ekf_node]: Cannot locate node of type [ekf_node] in package [robot_localization]. Make sure file exists in package path and permission is set to executable (chmod +x)

robot_localozationを変更してみてroslaunch igvc2023 start_sim.launchを実行したときこのエラーが出るのですが解決方法がわからないです、、。

**Comment by koki0624** [comment]
> RROR: cannot launch node of type [robot_localization/ekf_node]: Cannot locate node of type [ekf_node] in package [robot_localization]. Make sure file exists in package path and permission is set to executable (chmod +x)
> 
> robot_localozationを変更してみてroslaunch igvc2023 start_sim.launchを実行したときこのエラーが出るのですが解決方法がわからないです、、。

まずはエラーの内容をよく読んで、原因をさぐりましょう。エラー文で言われていることは必ずしも適切とは限りませんが、今回の場合は確認すべきことを提示してくれています。
また、解決のために試したことがあればそれも書いてもらえると助かります。

**Comment by kengohozumi** [comment]
ekf_node.pyに権限は与えたのですが直りませんでした、　chmod 777ではpythonはダメですか？

**Comment by Alpaca-zip** [comment]
> 適用する前のオドメトリと後のオドメトリを比較するというのはrobot_pose_ekfとrobot_localizationを比較するという意味でしょうか？

いえ、違います。robot_localizationがsubscribeする`/odom`とpublishしている`/odometry/filtered`を比較してみてください。

**Comment by koki0624** [comment]
> ekf_node.pyに権限は与えたのですが直りませんでした、　chmod 777ではpythonはダメですか？

ekf_node.py というファイルがあるんでしょうか？一度プルリクエストしてもらった方がいいかもです。

**Comment by Alpaca-zip** [comment]
@kengohozumi そもそもなんだけど、noetic-develをcloneしていますか？

**Comment by kengohozumi** [comment]
すみません　間違えてrobot_localizationをsrc内にgitcloneしてやっていてrobot_localization_nodeが使えない状況でした。
sudo apt-get install -y ros-noetic-robot-localizationでやってみます

GPSも使う関係で
<param name="odom0" value="/your_state_estimation_node_topic"> のコードが必要でyour_state_estimation_node_topicはigvc2023のtopicでどれになりますか？

http://docs.ros.org/en/melodic/api/robot_localization/html/integrating_gps.html

**Comment by kengohozumi** [comment]
> > 適用する前のオドメトリと後のオドメトリを比較するというのはrobot_pose_ekfとrobot_localizationを比較するという意味でしょうか？
> 
> いえ、違います。robot_localizationがsubscribeする`/odom`とpublishしている`/odometry/filtered`を比較してみてください。

わかりました　どちらもrostopic echoで比較すればいいですよね　やってみます

**Comment by Alpaca-zip** [comment]
@kengohozumi 
>すみません　間違えてrobot_localizationをsrc内にgitcloneしてやっていてrobot_localization_nodeが使えない状況でした。
sudo apt-get install -y ros-noetic-robot-localizationでやってみます

やっていることは間違っていませんよー。src以下にcloneしてビルドすれば使えるはずです。
___
>GPSも使う関係で
のコードが必要でyour_state_estimation_node_topicはigvc2023のtopicでどれになりますか？
http://docs.ros.org/en/melodic/api/robot_localization/html/integrating_gps.html

上記の記事から推測するにnav_msgs/Odometry型のオドメトリトピックです。`/odom`でいいと思います。

**Comment by Alpaca-zip** [comment]
> > > 適用する前のオドメトリと後のオドメトリを比較するというのはrobot_pose_ekfとrobot_localizationを比較するという意味でしょうか？
> > 
> > 
> > いえ、違います。robot_localizationがsubscribeする`/odom`とpublishしている`/odometry/filtered`を比較してみてください。
> 
> わかりました　どちらもrostopic echoで比較すればいいですよね　やってみます

Rvizで表示させて比べたほうが分かりやすいと思いますー。

**Comment by kengohozumi** [comment]
すいません　まだgithubに慣れてなくてcomitとpushが変になってるかもしれないです、、
一応今エラーが出てなくてrobot_localizationの実行ができました。rosrun rqt_tf_tree rqt_tf_treeを確認した際、数字が動いていたのですが確認をお願いしたいです。

**Comment by kengohozumi** [comment]
IGVC srcにcommitとpushしました

**Comment by Alpaca-zip** [comment]
もしかして`fixrobotlocalization`ブランチですか？
昨日も#17 で言ったけど、同じ編集内容のbranchを増やさないように注意してください。
このissueに割り当てられているPRは#15 でbranchは`feature/ekf_localizaton`です。

**Comment by kengohozumi** [comment]
自分でブランチの名前を
つけてcomitとpullすると思っていました
すみません　
mainからどうやってそのブランチの移動、編集ができますか？

**Comment by Alpaca-zip** [comment]
>もしかしてfixrobotlocalizationブランチですか？
昨日もhttps://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/pull/17 で言ったけど、同じ編集内容のbranchを増やさないように注意してください。
このissueに割り当てられているPRはhttps://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src/pull/15 でbranchはfeature/ekf_localizatonです。

少し面倒だけど、 #19 はcloseして`fixrobotlocalization`ブランチは削除してください。
`feature/ekf_localizaton`に再度commitとpushをしてから、 #15 にRe-requestしてください。

**Comment by kengohozumi** [comment]
feature/ekf_localizatonと同じ名前のブランチを作ってそこで編集するという意味ですか？

**Comment by Alpaca-zip** [comment]
> 自分でブランチの名前を つけてcomitとpullすると思っていました すみません　 mainからどうやってそのブランチの移動、編集ができますか？

新しく何かを編集するのであれば、自分で新しいbranchを作ってほしいですが、同じ編集内容のbranchを新しく作ることは極力避けてくれると助かります。もしくは、古いbranchとPRを削除してから新しくbranchを作ってください。
今回の場合は、`feature/ekf_localizaton`で編集を進めてもらうのが適切だと思います。

**以下、手順です。**
1. 一度自分が編集した内容(ファイルやフォルダ)をどこか別の場所に逃がしておく。
2. IGVC2023-srcのディレクトリで`git fetch`。
3. 一旦、`git pull origin main`。
4. ローカル環境に`feature/ekf_localizaton`というbranchを作ってcurrent branchを`feature/ekf_localizaton`に切り替える。
5. `git pull origin feature/ekf_localizaton`を実行。競合が発生した場合には、発生個所を修正して同じコマンド。
6. 自分が編集した内容を反映させて、`git commit`と`git push --set-upstream origin feature/ekf_localizaton`

か、もしくは上記が難しそうであれば、
1. 一度自分が編集した内容(ファイルやフォルダ)をどこか別の場所に逃がしておく。
2. 一旦、IGVC2023-srcを削除。
3. `git clone -b feature/ekf_localizaton https://github.com/KBKN-Autonomous-Robotics-Lab/IGVC2023-src.git`
4. `git pull origin main`を実行。競合が発生した場合には、発生個所を修正して同じコマンド。
5. 自分が編集した内容を反映させて、`git commit`と`git push --set-upstream origin feature/ekf_localizaton`

**Comment by kengohozumi** [comment]
わかりました　ありがとうございます

**Comment by Alpaca-zip** [comment]
> わかりました　ありがとうございます

私もGitを完全に理解しているわけじゃないから、上記のコマンドで上手くいかないこともあると思うので何でも聞いてくださいー。
