### ISSUE TITLE
シュミレーションの質問

### ISSUE THREAD

**Issue by kengohozumi** [KBKN-Autonomous-Robotics-Lab/IGVC2023-src#8]
今IGVCのworldファイルとurdfファイルをつなげるlanchファイルを作っているのですがworldファイルが表示されないのですが、、
プログラムは下のように書きました。
IGVCsimulation.launch

<?xml version="1.0"?>
<launch>
  ](url)
  <arg name="model" default="$(find tsukuba2022)/urdf/orange2022.xacro"/>
 

  
  <include file="$(find gazebo_ros)/launch/empty_world.launch">
    <arg name="world_name" value="$(find tsukuba2022)/worlds/course_v2.world"/>
    
  </include>

  <param name="robot_description" command="$(find xacro)/xacro $(arg model)" />

  
  <node name="urdf_spawner" pkg="gazebo_ros" type="spawn_model"
      args="-z 1.0 -unpause -urdf -model robot -param robot_description" respawn="false" output="screen" />
</launch>

**Comment by Alpaca-zip** [comment]
作業内容が分からないので一旦commitしてください。

**Comment by Alpaca-zip** [comment]
@kengohozumi 作業内容が分からないので一旦commitとpushお願いします。

**Comment by kengohozumi** [comment]
今commitとpushしました。

**Comment by Alpaca-zip** [comment]
@kengohozumi
`<arg name="world_name" value="$(find tsukuba2022)/worlds/course.world"/> `とありますが、正しくは`<arg name="world_name" value="$(find tsukuba2022)/world/course.world"/> `だと思います。一旦これで実行してみてくださいー。

**Comment by koki0624** [comment]
@kengohozumi start_sim.launchをベースに変更した方が、問題はあまりないと思うよ。

**Comment by kengohozumi** [comment]
worldsをworldに直したら出来ました。ありがとうございました。
ロボットが原点にいるのですがそれはどこで調節できますか？

**Comment by Alpaca-zip** [comment]
> worldsをworldに直したら出来ました。ありがとうございました。 ロボットが原点にいるのですがそれはどこで調節できますか？

start_sim.launchの中を見てもらえれば分かりますが、`-param robot_description -x $(arg x) -y $(arg y) -z $(arg z) -R $(arg roll) -P $(arg pitch) -Y $(arg yaw)`で指定できます。
